title: Spatial Engine
email: luizgabriel.info@gmail.com
description: >-
  Spatial is a cross-platform C++ game engine created on top off google's filament rendering engine.
  This projects uses C++17 and modern cmake features.
baseurl: "/Spatial.Engine"
url: "https://luizgabriel.github.io"
github_username: luizgabriel

# Build settings
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
color_scheme: dark

back_to_top: true
back_to_top_text: "Back to top"

logo: "/assets/images/logo.png"

aux_links:
  "GitHub":
    - "https://github.com/luizgabriel/Spatial.Engine"

aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/luizgabriel/Spatial.Engine"

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: false
      search_exclude: false