# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "jekyll", "~> 4.3"

gem "just-the-docs", "~> 0.4.0"

gem "jekyll-coffeescript", "~> 2.0"

gem "jekyll-default-layout", "~> 0.1.5"

gem "jekyll-gist", "~> 1.5"

gem "jekyll-github-metadata", "~> 2.15"

gem "jekyll-optional-front-matter", "~> 0.3.2"

gem "jekyll-paginate", "~> 1.1"

gem "jekyll-readme-index", "~> 0.3.0"

gem "jekyll-titles-from-headings", "~> 0.5.3"

gem "jekyll-relative-links", "~> 0.7.0"

gem "kramdown-parser-gfm", "~> 1.1"

