name: Build

on:
  push:
    branches:
      - master
      - feature/*
      - release/*
    tags:
      - 'v*'

env:
  CONAN_SYSREQUIRES_MODE: enabled

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Ubuntu-Clang", os: ubuntu-20.04, gen: "Ninja" }
          - { name: "MacOS-Clang", os: macos-11, gen: "CodeBlocks - Unix Makefiles" }
          - { name: "Windows-MSVC", os: windows-2019, gen: "Visual Studio 16 2019", cc: "cl", cxx: "cl" }

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ">= 3.5"

      - name: (Windows) Setup MSBuild
        if: matrix.config.os == 'windows-2019'
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: (Ubuntu) Install Ninja
        if: matrix.config.os == 'ubuntu-20.04'
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.10.2

      - name: (Ubuntu) Set up Clang
        if: matrix.config.os == 'ubuntu-20.04'
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: (Ubuntu) Conan - Configure Ninja
        if: matrix.config.os == 'ubuntu-20.04'
        shell: bash
        run: conan config set general.cmake_generator=Ninja

      - name: Cache Conan Data
        uses: actions/cache@v3
        with:
          path: ~/.conan/
          key: ${{ runner.os }}-${{ hashFiles('conanfile.py') }}

      - name: Configure
        shell: bash
        run: python $GITHUB_WORKSPACE/cli.py configure --build-type=Release --build-tests

      - name: Build
        shell: bash
        run: python $GITHUB_WORKSPACE/cli.py build --build-type=Release

      - name: Run Tests
        working-directory: out/build/Spatial.Core/tests
        shell: bash
        run: ./Spatial.Core.Tests

      - name: Install
        shell: bash
        run: python $GITHUB_WORKSPACE/cli.py install --build-type=Release

      - name: Get the version
        if: contains(github.ref, 'tags/v')
        id: get_version
        shell: bash
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Upload artifacts
        if: contains(github.ref, 'tags/v')
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.name }}-${{ steps.get_version.outputs.VERSION }}.tar.xz
          path: out/install/*

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2

      - name: Upload to Release
        uses: meeDamian/github-release@2.0
        with:
          files: ${{ matrix.config.name }}-${{ steps.get_version.outputs.VERSION }}.tar.xz
          gzip: folders
          token: ${{ secrets.GITHUB_TOKEN }}