name: Build

on:
  push:
    branches:
      - master
      - feature/*
      - release/*
    tags:
      - 'v*'

env:
  CONAN_SYSREQUIRES_MODE: enabled

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Ubuntu-Clang", os: ubuntu-20.04, gen: "Ninja", cc: "clang", cxx: "clang++" }
          - { name: "MacOS-Clang", os: macos-11, gen: "'CodeBlocks - Unix Makefiles'", cc: "clang", cxx: "clang++" }
          # - { name: "Windows-MSVC", os: windows-2019, gen: "'Visual Studio 16 2019'", cc: "cl", cxx: "cl" }

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ">= 3.5"

      - name: Setup MSBuild
        if: matrix.config.os == 'windows-2019'
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Install Ninja
        if: matrix.config.os == 'ubuntu-20.04'
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.10.2

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Setup Vendor Packages
        run: |
          python3 $GITHUB_WORKSPACE/setup.py

      - name: Cache Conan Data
        uses: actions/cache@v2
        with:
          path: ~/.conan/
          key: ${{ runner.os }}-${{ hashFiles('conanfile.py') }}

      - name: Build & Test
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build/
          cc: ${{ matrix.config.cc }}
          cxx: ${{ matrix.config.cxx }}
          build-type: Release
          configure-options: -G '${{ matrix.config.gen }}' -DSPATIAL_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=${{ runner.workspace }}/install
          run-test: true
          install-build: true
          parallel: 14

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Upload artifacts
        if: contains(github.ref, 'tags/v')
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.name }}-${{ steps.get_version.outputs.VERSION }}.zip
          path: ${{runner.workspace}}/install/*

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Upload to Release
        uses: meeDamian/github-release@2.0
        with:
          files: ${{ matrix.config.name }}-${{ steps.get_version.outputs.VERSION }}.zip
          gzip: folders
          token: ${{ secrets.GITHUB_TOKEN }}