name: Build

on:
  push:
    branches:
      - master
      - rc/*
    tags:
      - 'v*'

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ${{ matrix.config.os }}
    outputs:
      tag: ${{ steps.get_version.outputs.tag }}
    strategy:
      matrix:
        config:
          # - { name: "Ubuntu-Clang", os: ubuntu-20.04, build_type: "Release", conan_preset: "conan-release" }
          - { name: "MacOS-Clang", os: macos-14, build_dir: "build/Release", config_preset: "conan-release", build_preset: "conan-release" }
          - { name: "Windows-MSVC", os: windows-2022, build_dir: "build", config_preset: "conan-default", build_preset: "conan-release" }

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ">= 3.10"

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: (Windows) Setup MSBuild
        if: contains(matrix.config.os, 'windows')
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: (Windows) Setup Windows Dependencies
        if: contains(matrix.config.os, 'windows')
        shell: bash
        run: choco install windows-sdk-10-version-2004-windbg wixtoolset

      - name: (Linux) Setup Linux Dependencies
        if: contains(matrix.config.os, 'ubuntu')
        shell: bash
        run: |
          sudo apt-get install libglu1-mesa-dev libxi-dev libxcomposite-dev libxxf86vm-dev libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev
          sudo apt-get install libxaw7-dev libxcursor-dev libxdamage-dev libxinerama-dev libxmuu-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxvmc-dev
          sudo apt-get install libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-util-dev

      - name: (Linux) Set up Clang
        if: contains(matrix.config.os, 'ubuntu')
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Read Conan Profile
        id: conan_profile
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: .github/workflows/profiles/${{ matrix.config.name }}.txt

      - name: Set up Conan Profile
        shell: bash
        run: |
          conan profile detect
          echo "Overwriting Conan Profile with: ${{ steps.conan_profile.outputs.content }}"
          echo "${{ steps.conan_profile.outputs.content }}" > $(conan profile path default)

      - name: (Conan) Build Dependencies
        shell: bash
        run: |
          conan install . --build=missing
      
      - name: (Cmake) Configure
        shell: bash
        run: cmake --preset ${{ matrix.config.config_preset }}

      - name: (Cmake) Build
        shell: bash
        run: cmake --build . --preset ${{ matrix.config.build_preset }}

      - name: (CTest) Run Tests
        shell: bash
        run: ctest . --preset ${{ matrix.config.build_preset }} -E "(Application|PhysicalFileSystem)" --output-on-failure

      - name: (CPack) Generate Package
        if: contains(github.ref, 'refs/tags/')
        shell: bash
        run: cmake --build . --preset ${{ matrix.config.build_preset }} --target package

      - name: Get Version Tag
        id: get_version
        shell: bash
        run: |
          if [[ "${{ github.ref }}" =~ tags/(.*) ]]; then
              echo "tag=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
          else
              echo "tag=${{ github.run_id }}" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Upload artifacts
        if: contains(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.name }}-${{ steps.get_version.outputs.tag }}
          if-no-files-found: error
          path: |
            build/package/*.msi
            build/Release/package/*.dmg  
            build/Release/package/*.deb
      
  release:
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        id: download
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List Artifacts
        run: ls -R ${{ steps.download.outputs.download-path }}

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build.outputs.tag }}
          files: ${{ steps.download.outputs.download-path }}/*
          draft: false
          prerelease: false