name: Build

on:
  push:
    branches:
      - master
      - feature/*
      - release/*
    tags:
      - 'v*'

env:
  CONAN_SYSREQUIRES_MODE: enabled

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Ubuntu-Clang", os: ubuntu-20.04, gen: "Ninja" }
          - { name: "MacOS-Clang", os: macos-11, gen: "CodeBlocks - Unix Makefiles" }
          - { name: "Windows-MSVC", os: windows-2019, gen: "Visual Studio 16 2019", cc: "cl", cxx: "cl" }

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ">= 3.5"

      - name: Setup MSBuild
        if: matrix.config.os == 'windows-2019'
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Install Ninja
        if: matrix.config.os == 'ubuntu-20.04'
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.10.2

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Setup Vendor Packages
        run: |
          python3 $GITHUB_WORKSPACE/setup.py

      - name: Cache Conan Data
        uses: actions/cache@v2
        with:
          path: ~/.conan/
          key: ${{ runner.os }}-${{ hashFiles('conanfile.py') }}

      - name: Cmake Configure
        shell: bash
        run: >-
          cmake
          -B out/build
          -S $GITHUB_WORKSPACE
          -G "${{ matrix.config.gen }}"
          -DCMAKE_BUILD_TYPE=Release
          -DSPATIAL_BUILD_TESTS=ON
          -DCMAKE_INSTALL_PREFIX=out/install

      - name: Cmake Build
        working-directory: out/build
        shell: bash
        run: cmake --build . --config Release --target all

      - name: Run Tests
        working-directory: out/build/Spatial.Core/tests
        shell: bash
        run: ./Spatial.Core.Tests

      - name: Cmake Install
        working-directory: out/build
        shell: bash
        run: cmake --build . --config Release --target install

      - name: Get the version
        if: contains(github.ref, 'tags/v')
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Upload artifacts
        if: contains(github.ref, 'tags/v')
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.name }}-${{ steps.get_version.outputs.VERSION }}.tar.xz
          path: ${{ runner.workspace }}/out/install/*

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Upload to Release
        uses: meeDamian/github-release@2.0
        with:
          files: ${{ matrix.config.name }}-${{ steps.get_version.outputs.VERSION }}.tar.xz
          gzip: folders
          token: ${{ secrets.GITHUB_TOKEN }}