name: Build

on:
  push:
    branches:
      - master
      - feature/*
      - release/*
    tags:
      - 'v*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          # - { name: "Ubuntu-Clang", os: ubuntu-20.04, preset: "Linux-Release" }
          - { name: "MacOS-Clang", os: macos-11, preset: "MacOS-Release" }
          - { name: "Windows-MSVC", os: windows-2022, preset: "Windows-Release" }
          - { name: "Windows-2019-MSVC", os: windows-2019, preset: "Windows-2019-Release" }

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ">= 3.5"

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: (Windows) Setup MSBuild
        if: contains(matrix.config.os, 'windows')
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: (Windows) Setup Windows 10 SDK 10.0.19041.0
        if: contains(matrix.config.os, 'windows')
        shell: bash
        run: choco install windows-sdk-10-version-2004-windbg

      - name: (Linux) Setup Linux Dependencies
        if: contains(matrix.config.os, 'ubuntu')
        shell: bash
        run: sudo apt-get install ninja-build mesa-common-dev libxi-dev libxxf86vm-dev

      - name: (Ubuntu) Set up Clang
        if: contains(matrix.config.os, 'ubuntu')
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Configure
        shell: bash
        run: python $GITHUB_WORKSPACE/cli.py configure --preset=${{ matrix.config.preset }}

      # - name: Conan Upload Binary Artifacts
      #   shell: bash
      #   run: |
      #     conan user -p ${{ secrets.CONAN_REPOSITORY_SECRET_TOKEN }} -r spatial ${{ secrets.CONAN_REPOSITORY_USERNAME }}
      #     conan upload v8 -r spatial --all --confirm --retry 3 --retry-wait 10
      #     conan upload filament -r spatial --all --confirm --retry 3 --retry-wait 10

      - name: Build
        shell: bash
        run: python $GITHUB_WORKSPACE/cli.py build --preset=${{ matrix.config.preset }}

      - name: Run Tests
        working-directory: ${{ github.workspace }}
        shell: bash
        run: python ./cli.py test --preset=${{ matrix.config.preset }}

      - name: Install
        if: contains(github.ref, 'tags/v')
        shell: bash
        run: python $GITHUB_WORKSPACE/cli.py install --preset=${{ matrix.config.preset }}

      - name: Get the version
        if: contains(github.ref, 'tags/v')
        id: get_version
        shell: bash
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Upload artifacts
        if: contains(github.ref, 'tags/v')
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.config.name }}-${{ steps.get_version.outputs.VERSION }}
          path: out/install/${{ matrix.config.preset }}/*
          if-no-files-found: error

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Get the version
        id: get_version
        shell: bash
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Download artifact
        uses: actions/download-artifact@v3

      - name: Upload to Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          gzip: folders
          files: >
            MacOS-Clang-${{ steps.get_version.outputs.VERSION }}
            Windows-MSVC-${{ steps.get_version.outputs.VERSION }}
            Windows-2019-MSVC-${{ steps.get_version.outputs.VERSION }}
